// Tüm ülkelerin listesi
export const countries = [
  'Türkiye',
  'Afganistan',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'Arjantin',
  'Avustralya',
  'Avusturya',
  'Azerbaycan',
  'Bahreyn',
  'Bangladeş',
  'Belarus',
  'Belçika',
  'Birleşik Arap Emirlikleri',
  'Birleşik Krallık',
  'Brezilya',
  'Bulgaristan',
  'Çin',
  'Danimarka',
  'Endonezya',
  'Ermenistan',
  'Estonya',
  'Fas',
  'Filipinler',
  'Finlandiya',
  'Fransa',
  'Gana',
  'Güney Afrika',
  'Güney Kore',
  'Hindistan',
  'Hollanda',
  'İran',
  'İrlanda',
  'İspanya',
  'İsrail',
  'İsveç',
  'İsviçre',
  'İtalya',
  'Japonya',
  'Kanada',
  'Katar',
  'Kazakistan',
  'Kenya',
  'Kolombiya',
  'Kuveyt',
  'Kuzey Kore',
  'Küba',
  'Letonya',
  'Litvanya',
  'Lübnan',
  'Macaristan',
  'Malezya',
  'Meksika',
  'Mısır',
  'Norveç',
  'Pakistan',
  'Peru',
  'Polonya',
  'Portekiz',
  'Romanya',
  'Rusya',
  'Singapur',
  'Slovakya',
  'Slovenya',
  'Suudi Arabistan',
  'Şili',
  'Tayland',
  'Tunus',
  'Ukrayna',
  'Umman',
  'Ürdün',
  'Venezuela',
  'Vietnam',
  'Yeni Zelanda',
  'Yunanistan'
]
